-- load modular configs
require('config.key-mapping')
require('config.plugins')
require('config.settings')
require('config.colorscheme')

-- setup plugins
require('config.impatient')
require('config.which-key')
require('config.alpha_config')
require('config.lualine')
require('config.lspconfig')
require('config.treesitter')
require('config.cmp')
require('config.nvim-tree')
require('config.autopairs')
require('config.luasnip')
require('config.comment')
require('config.livecommand')
require('config.key-mapping')
require('config.dressing')
require('config.lightbulb')
require('config.dap')
require('config.telescope')
-- vim: ts=2 sts=2 sw=2 et
