-- local nvim_jdtls, ok = pcall(require, "jdtls")
-- if not ok then
--   return
-- end
-- local config = {
--     cmd = {'/path/to/jdt-language-server/bin/jdtls'},
--     root_dir = vim.fs.dirname(vim.fs.find({'gradlew', '.git', 'mvnw'}, { upward = true })[1]),
-- }
-- nvim_jdtls.start_or_attach(config)
